stages:
  download_data:
    cmd: python src/data/import_raw_data.py
    deps:
    - src/data/import_raw_data.py
    outs:
    - data/raw_data/raw.csv
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw_data/raw.csv
    - src/data/make_dataset.py
    outs:
    - data/processed_data
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data
    - src/models/train_model.py
    outs:
    - models/best_params.pkl
    - models/scaler.pkl
    - models/trained_model.joblib
  evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/scaler.pkl
    - models/trained_model.joblib
    - src/models/evaluate_model.py
    metrics:
    - metrics/scores.json:
        cache: false
